/**
 * Project-local PATH wraps for package managers.
 *
 * MCP remains advisory. These shims close the common bypass where an agent
 * shells out to bare `npm install` / `pip install` instead of `juno …`.
 * Absolute paths to the real binary still bypass the wrap — that residual is
 * intentional and documented.
 */

import {
  accessSync,
  chmodSync,
  constants,
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { delimiter, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const WRAP_MANAGERS = ["npm", "pnpm", "yarn", "pip"] as const;
export type WrapManager = (typeof WRAP_MANAGERS)[number];

export function wrapDir(cwd = process.cwd()): string {
  return join(resolve(cwd), ".junoguard", "bin");
}

export function shimPath(manager: WrapManager, cwd = process.cwd()): string {
  return join(wrapDir(cwd), manager);
}

function defaultBinPath(): string {
  return fileURLToPath(new URL("./bin.js", import.meta.url));
}

function shimScript(
  manager: WrapManager,
  nodePath: string,
  binPath: string,
  dir: string,
): string {
  return `#!/bin/sh
# Generated by juno wrap — do not edit.
export JUNO_WRAP_DIR="${dir}"
exec "${nodePath}" "${binPath}" ${manager} "$@"
`;
}

export function enableWrap(options: {
  cwd?: string;
  nodePath?: string;
  binPath?: string;
} = {}): { dir: string; created: string[] } {
  const cwd = options.cwd ?? process.cwd();
  const dir = wrapDir(cwd);
  const nodePath = options.nodePath ?? process.execPath;
  const binPath = options.binPath ?? defaultBinPath();
  mkdirSync(dir, { recursive: true });
  const created: string[] = [];
  for (const manager of WRAP_MANAGERS) {
    const path = shimPath(manager, cwd);
    writeFileSync(path, shimScript(manager, nodePath, binPath, dir), { encoding: "utf8" });
    chmodSync(path, 0o755);
    created.push(path);
  }
  return { dir, created };
}

function removeIfEmpty(path: string): void {
  try {
    if (existsSync(path) && readdirSync(path).length === 0) rmSync(path);
  } catch {
    // Best-effort cleanup only.
  }
}

export function disableWrap(cwd = process.cwd()): { dir: string; removed: string[] } {
  const dir = wrapDir(cwd);
  const removed: string[] = [];
  for (const manager of WRAP_MANAGERS) {
    const path = shimPath(manager, cwd);
    if (!existsSync(path)) continue;
    rmSync(path);
    removed.push(path);
  }
  removeIfEmpty(dir);
  removeIfEmpty(dirname(dir));
  return { dir, removed };
}

export function wrapStatus(cwd = process.cwd()): {
  dir: string;
  active: WrapManager[];
  missing: WrapManager[];
  pathPrefixed: boolean;
} {
  const dir = wrapDir(cwd);
  const active = WRAP_MANAGERS.filter((manager) => existsSync(shimPath(manager, cwd)));
  const missing = WRAP_MANAGERS.filter((manager) => !active.includes(manager));
  const pathEntries = (process.env.PATH ?? "").split(delimiter).filter(Boolean);
  const pathPrefixed = pathEntries.some((entry) => resolve(entry) === resolve(dir));
  return { dir, active, missing, pathPrefixed };
}

/**
 * Find the real package manager, skipping the wrap directory so an allow
 * decision cannot recurse back into the shim.
 */
export function resolveRealBinary(
  manager: string,
  env: NodeJS.ProcessEnv = process.env,
): string {
  const override = env[`JUNO_REAL_${manager.toUpperCase()}`];
  if (override) return override;

  const wrap = env.JUNO_WRAP_DIR ? resolve(env.JUNO_WRAP_DIR) : null;
  for (const dir of (env.PATH ?? "").split(delimiter)) {
    if (!dir) continue;
    if (wrap && resolve(dir) === wrap) continue;
    const candidate = join(dir, manager);
    try {
      accessSync(candidate, constants.X_OK);
      return candidate;
    } catch {
      // Keep scanning PATH.
    }
  }
  return manager;
}
